//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TixGurusWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeatBooking()
        {
            this.Bookings = new HashSet<Booking>();
        }
    
        public int SeatBookingID { get; set; }
        public int EventID { get; set; }
        public bool Booked { get; set; }
        public int SeatID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual Event Event { get; set; }
        public virtual Seat Seat { get; set; }
    }
}
